export const mockFlights = [
  // Outbound flights
  {
    id: 1,
    number: "CW954",
    aircraft: "B777",
    departureAirport: "BEY",
    departureTime: "19:40",
    departureDate: "2024-08-01",
    arrivalAirport: "BAH",
    arrivalTime: "02:15",
    arrivalDate: "2024-08-02",
    duration: "6 hrs 35 mins",
    economyPrice: 381.7,
    businessPrice: 1267.7,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "outbound",
  },
  {
    id: 2,
    number: "CW835",
    aircraft: "A320",
    departureAirport: "BEY",
    departureTime: "10:15",
    departureDate: "2024-08-05",
    arrivalAirport: "BAH",
    arrivalTime: "16:45",
    arrivalDate: "2024-08-05",
    duration: "6 hrs 30 mins",
    economyPrice: 405.5,
    businessPrice: 1350.0,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "outbound",
  },
  {
    id: 3,
    number: "CW762",
    aircraft: "B737",
    departureAirport: "BEY",
    departureTime: "14:30",
    departureDate: "2024-08-10",
    arrivalAirport: "BAH",
    arrivalTime: "21:00",
    arrivalDate: "2024-08-10",
    duration: "6 hrs 30 mins",
    economyPrice: 392.8,
    businessPrice: 1300.9,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "outbound",
  },
  {
    id: 7,
    number: "CW959",
    aircraft: "B787",
    departureAirport: "BEY",
    departureTime: "22:00",
    departureDate: "2024-08-15",
    arrivalAirport: "BAH",
    arrivalTime: "04:45",
    arrivalDate: "2024-08-16",
    duration: "6 hrs 45 mins",
    economyPrice: 410.0,
    businessPrice: 1400.0,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "outbound",
  },
  {
    id: 8,
    number: "CW850",
    aircraft: "A321",
    departureAirport: "BEY",
    departureTime: "06:00",
    departureDate: "2024-08-20",
    arrivalAirport: "BAH",
    arrivalTime: "12:30",
    arrivalDate: "2024-08-20",
    duration: "6 hrs 30 mins",
    economyPrice: 370.0,
    businessPrice: 1250.0,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "outbound",
  },
  // Inbound flights
  {
    id: 4,
    number: "CW958",
    aircraft: "B777",
    departureAirport: "BAH",
    departureTime: "08:30",
    departureDate: "2024-08-15",
    arrivalAirport: "BEY",
    arrivalTime: "13:00",
    arrivalDate: "2024-08-15",
    duration: "6 hrs 30 mins",
    economyPrice: 381.7,
    businessPrice: 1267.7,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "inbound",
  },
  {
    id: 5,
    number: "CW836",
    aircraft: "A320",
    departureAirport: "BAH",
    departureTime: "23:00",
    departureDate: "2024-08-20",
    arrivalAirport: "BEY",
    arrivalTime: "04:30",
    arrivalDate: "2024-08-21",
    duration: "6 hrs 30 mins",
    economyPrice: 405.5,
    businessPrice: 1350.0,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "inbound",
  },
  {
    id: 6,
    number: "CW763",
    aircraft: "B737",
    departureAirport: "BAH",
    departureTime: "17:45",
    departureDate: "2024-08-25",
    arrivalAirport: "BEY",
    arrivalTime: "23:15",
    arrivalDate: "2024-08-25",
    duration: "6 hrs 30 mins",
    economyPrice: 392.8,
    businessPrice: 1300.9,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "inbound",
  },
  {
    id: 9,
    number: "CW960",
    aircraft: "B787",
    departureAirport: "BAH",
    departureTime: "15:00",
    departureDate: "2024-08-30",
    arrivalAirport: "BEY",
    arrivalTime: "21:30",
    arrivalDate: "2024-08-30",
    duration: "6 hrs 30 mins",
    economyPrice: 410.0,
    businessPrice: 1400.0,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "inbound",
  },
  {
    id: 10,
    number: "CW851",
    aircraft: "A321",
    departureAirport: "BAH",
    departureTime: "09:15",
    departureDate: "2024-08-25",
    arrivalAirport: "BEY",
    arrivalTime: "15:45",
    arrivalDate: "2024-08-25",
    duration: "6 hrs 30 mins",
    economyPrice: 370.0,
    businessPrice: 1250.0,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "inbound",
  },
];
