export const mockFlights = [
  // Outbound flights
  {
    id: 1,
    number: "CW954",
    aircraft: "B777",
    departureAirport: "BEY",
    departureTime: "19:40",
    arrivalAirport: "BAH",
    arrivalTime: "02:15",
    duration: "6 hrs 35 mins",
    economyPrice: 381.7,
    businessPrice: 1267.7,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "outbound",
  },
  {
    id: 2,
    number: "CW835",
    aircraft: "A320",
    departureAirport: "BEY",
    departureTime: "10:15",
    arrivalAirport: "BAH",
    arrivalTime: "16:45",
    duration: "6 hrs 30 mins",
    economyPrice: 405.5,
    businessPrice: 1350.0,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "outbound",
  },
  {
    id: 3,
    number: "CW762",
    aircraft: "B737",
    departureAirport: "BEY",
    departureTime: "14:30",
    arrivalAirport: "BAH",
    arrivalTime: "21:00",
    duration: "6 hrs 30 mins",
    economyPrice: 392.8,
    businessPrice: 1300.9,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "outbound",
  },
  // Inbound flights
  {
    id: 4,
    number: "CW958",
    aircraft: "B777",
    departureAirport: "BAH",
    departureTime: "08:30",
    arrivalAirport: "BEY",
    arrivalTime: "13:00",
    duration: "6 hrs 30 mins",
    economyPrice: 381.7,
    businessPrice: 1267.7,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "inbound",
  },
  {
    id: 5,
    number: "CW836",
    aircraft: "A320",
    departureAirport: "BAH",
    departureTime: "23:00",
    arrivalAirport: "BEY",
    arrivalTime: "04:30",
    duration: "6 hrs 30 mins",
    economyPrice: 405.5,
    businessPrice: 1350.0,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "inbound",
  },
  {
    id: 6,
    number: "CW763",
    aircraft: "B737",
    departureAirport: "BAH",
    departureTime: "17:45",
    arrivalAirport: "BEY",
    arrivalTime: "23:15",
    duration: "6 hrs 30 mins",
    economyPrice: 392.8,
    businessPrice: 1300.9,
    economyWeight: "23 kg",
    economyMeals: 1,
    businessWeight: "32 kg",
    businessMeals: 2,
    economyCabinBaggage: "1 x 7kg",
    businessCabinBaggage: "2 x 7kg",
    economyChangeFee: "Restricted",
    businessChangeFee: "No charge",
    economyRefundFee: "Restricted",
    businessRefundFee: "No charge",
    type: "inbound",
  },
];
